/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef TEST_BAKE_CONFIG_H
#define TEST_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_components_meta.h>
#ifdef __BAKE__
#include <bake_util.h>
#endif
#include <bake_test.h>

/* Headers of private dependencies */
#ifdef TEST_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef TEST_STATIC
  #if TEST_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define TEST_EXPORT __declspec(dllexport)
  #elif TEST_IMPL
    #define TEST_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define TEST_EXPORT __declspec(dllimport)
  #else
    #define TEST_EXPORT
  #endif
#else
  #define TEST_EXPORT
#endif

#endif

