/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef VECTOR_BAKE_CONFIG_H
#define VECTOR_BAKE_CONFIG_H

/* Headers of public dependencies */
#include <flecs.h>
#include <flecs_components_meta.h>

/* Headers of private dependencies */
#ifdef VECTOR_IMPL
/* No dependencies */
#endif

/* Convenience macro for exporting symbols */
#ifndef VECTOR_STATIC
  #if VECTOR_IMPL && (defined(_MSC_VER) || defined(__MINGW32__))
    #define VECTOR_EXPORT __declspec(dllexport)
  #elif VECTOR_IMPL
    #define VECTOR_EXPORT __attribute__((__visibility__("default")))
  #elif defined _MSC_VER
    #define VECTOR_EXPORT __declspec(dllimport)
  #else
    #define VECTOR_EXPORT
  #endif
#else
  #define VECTOR_EXPORT
#endif

#endif

