name: CI

on: [push, pull_request]

jobs:
  build-linux:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc: gcc-7
            cxx: g++-7
          - cc: gcc-8
            cxx: g++-8
          - cc: gcc-9
            cxx: g++-9
          - cc: gcc-10
            cxx: g++-10
          - cc: clang-8
            cxx: clang++-8
          - cc: clang-9
            cxx: clang++-9
          - cc: clang-10
            cxx: clang++-10

    steps:
      - uses: actions/checkout@v2
      - name: install compiler
        run: |
          sudo apt-get install -y ${{ matrix.compiler.cc }}
          sudo apt-get install -y ${{ matrix.compiler.cxx }}
      
      - name: install bake
        run: |
          git clone https://github.com/SanderMertens/bake
          make -C bake/build-$(uname)
          bake/bake setup

      - name: install flecs
        run: |
          git clone https://github.com/SanderMertens/flecs
          bake flecs

      - name: build (debug)
        run: |
          bake --strict --cfg debug

      - name: build (release)
        run: |          
          bake --strict --cfg release

      - name: build examples (debug)
        run: |
          bake examples --strict --cfg debug

      - name: build examples (release)
        run: |
          bake examples --strict --cfg release

  build-windows:
    timeout-minutes: 10
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1

      - name: install bake
        run: |
          git clone https://github.com/SanderMertens/bake
          cd bake\build-Windows
          nmake
          cd ..
          ./bake setup --local

      - name: install flecs
        run: |
          git clone https://github.com/SanderMertens/flecs
          bake flecs

      - name: build (debug)
        run: bake/bake --strict --cfg debug
        
      - name: build (release)
        run: bake/bake --strict --cfg release        

      - name: build examples (debug)
        run: |
          bake/bake examples --strict --cfg debug

      - name: build examples (release)
        run: |
          bake/bake examples --strict --cfg release

  test-unix:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: install bake
        run: |
          git clone https://github.com/SanderMertens/bake
          make -C bake/build-$(uname)
          bake/bake setup

      - name: install flecs
        run: |
          git clone https://github.com/SanderMertens/flecs
          bake flecs

      - name: build
        run: bake --strict

      - name: run tests
        run: |
          bake run test/serialize
          bake run test/deserializer
